### ISSUE TITLE
When using the print() function to output a float type variable it results in an int

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-fw#100]
When using the print() function to output a float type variable it results in an int type
![kép](https://github.com/user-attachments/assets/0ae26989-a8b2-4321-818f-ce4350ee8688)

But when using a concat operator right after that same variable, it properly outputs the float type
![kép](https://github.com/user-attachments/assets/9c00dcae-0e9d-4f68-bc83-2a25c0a52781)

**Comment by SukuWc** [comment]
fixed in nightly
