### ISSUE TITLE
Test the math lua library

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-fw#101]
https://www.lua.org/manual/5.3/manual.html#6.7

Test all functions if they work or not. Create a note where the functions are broken, possibly a profile that can test the library.

The output of this research will accelerate the FW development.

- ✅ math.abs(x) 
- ✅ math.acos(x)
- ✅ math.asin(x)
- ✅ math.asan(y [, x])
- ✅ math.ceil(x)
- ✅ math.cos(x)
- ✅ math.deg(x)
- ✅ math.exp(x)
- ✅ math.floor(x)
- ✅ math.fmod(x, y)
- ✅ math.huge
- ✅ math.log(x [, base]) 
- ✅ math.min(x, ...)
- ✅ math.minteger
- ✅ math.modf (x)
- ✅ math.pi
- ✅ math.rad(x)
- ❌ math.random ([m [, n]]) - LUA NOT OK error when using one or two arguments or no arguments at all
- ✅ math.randomseed(x)
- ✅ math.sin (x)
- ✅ math.sqrt(x)
- ✅ math.tan(x)
- ✅ math.tointeger(x)
- ✅ math.type (x)
- ❌ math.ult(m, n) - not implemented, doesn't even appear in monaco suggestion list when typing 'math. ..'
- ❓math.pow( ) doesn't work, use ^ operator instead. - this is ok, but would be nice if both were possible

**Comment by SukuWc** [comment]
pow is depricated, random is fixed in firmware, ult broken but will not fix
