### ISSUE TITLE
[Nightly] immediate_send() can't trigger Grid modules to send messages

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-fw#102]
When using a module to tell another to  send MIDI, keyboard or any type of message, the module on the receiving end will only be able to send the message if it's actively being interacted with.

As you can see the messages are only sent when an element on the module that is receiving the message from the EF44, is turned as well.
![is_bug](https://github.com/user-attachments/assets/1923e6dd-65a0-4ce9-b819-e55b982a716b)
(Ignore the modules crashing at the end.)

**Comment by SukuWc** [comment]
Fixed in nightly
