### ISSUE TITLE
Bug: the Timer UI event cannot launch a new timer more than once

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-fw#37]
Using the latest public firmware at the moment of writing (19 Mar 2023) I have seen experimentally that a Timer UI event cannot start a new timer more than once. It is not clear if it is a feature or a bug.

To reproduce on a BU16:
1) ensure that a button's Timer event outputs some debugging information, e.g. the default `print('tick')` 
2) add a timer start action to both 1) the button event and 2) the timer event 
3) press the button

The output will show 'tick' just twice.

The use case for this is automating the execution of CC changes over time, e.g. reducing a value by 5% every 10th of a second until it reaches zero.

**Comment by SukuWc** [comment]
I think the problem might be that it gets triggered on the button press and the release, but never on the actual timer event. Make sure that timer start on the timer event starts the actual elemet's timer! 

if Button4 starts Timer4 then the Time4 callback should also start Timer4 to create and infinite loop!
