### ISSUE TITLE
Init Events run in a sequential order at startup from control element index 0 to 255, this leads to unexpected behavior.

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-fw#42]
When trying to initialize global variables on Init, and using those variables on different Init Events leads to LUA errors. Errors appear when the index number of the control element is higher where the variable is initalized than the number of the control element where they are called.

For example, I create a variable `test=0` on the System Init event. This element bears the index number 255. I create a function on control element 0 that uses this global variable `print(test)`. Expected behavior from the user would be that on powerup the module prints 0 in the debug monitor.
Instead nothing happens, because the variable it's trying to use hasn't been initialzed yet.

This behavior is confusing, even though it's working as intended. Either this requires in-depth knowledge from the user to work around or it would require a fw-side fix so that variables declared on init events are always declared before functions can call them, even if variables and functions reside on non-succeeding control elements.

**Comment by SukuWc** [comment]
System element is now handled first with elevated priority! Check latest commit!
