### ISSUE TITLE
D51 encoder relative mode: rel 2's comp bugged

### ISSUE THREAD

**Issue by narayb** [intechstudio/grid-fw#46]
Instead of sending 1 and 127 values on encoder turns, the modules send out 65 value on each control change.

This bug was introduced with release firmware version [v1.2.21](https://github.com/intechstudio/grid-fw/releases/tag/v1.2.21) and is only present on D51 based modules.

Correction: on the newest firmware, all versions of Grid exhibit this behavior.

**Comment by SukuWc** [comment]
Could not reproduce, most likely already fixed!
