### ISSUE TITLE
Push Encoder behaviour issue on SAMD51 modules w/ firmware ≥ v1.2.25

### ISSUE THREAD

**Issue by mattcoffyn** [intechstudio/grid-fw#63]
### Issue Summary
Both my EN16 & EF44 modules have developed an issue with encoder behaviour. This is affecting all encoders on both modules. Press and Release of the button causes the encoder value to increase and triggers the Rotate Right action on the encoder's event. This only occurs on firmware versions v1.2.25 and higher.

### 1. Encoder Value Increase Details
On both button press and button release, encoder value increases by 76 (not 127 as previously thought). 

Example MIDI output on default EN16 profile below. Encoder set to CC 33 in absolute mode. Button set to MIDI note A1.

_Rotate left to confirm Encoder value_
`11:47:55.997		Control		1	33	0`

_Push Button_
`11:48:00.809		Control		1	33	76`
`11:48:00.832		Note On		1	A1	127`

_Release Button_
`11:48:05.301		Control		1	33	127`
`11:48:05.324		Note Off		1	A1	0`

_Rotate left to confirm Encoder value_
`11:48:07.777		Control		1	33	126`

Where encoder value is >0 before button press, it will increase by 76 (to max of 127) on both press and release. Tested by setting different encoder values before press, and by rotating between press and release (push and hold). 

This behaviour is also consistent regardless of action stored on the encoder event (including no action). E.g. on the same default profile, removing the MIDI block from the encoder event means no CC output is captured, but behaviour is confirmed through `self:encoder_value()` on LED or console print.

### 2. Action Trigger Issue Details
As well as the encoder value change, the button triggers the Rotate Right action on the encoder event. This is independent of actions (if any) stored on either the button or encoder.

The example in the screenshots below shows the debug output of the button press and release as well as the events for both button and encoder. 

_Note: When the editor is open and Interaction Tracking is set to Event, the UI also swtiches to the Encoder event on button press._

<img width="1331" alt="Screenshot 2023-11-02 at 12 30 37" src="https://github.com/intechstudio/grid-fw/assets/57856409/4513d45b-b34b-4c7f-b550-8a9a2c3ea87d">

<img width="1331" alt="Screenshot 2023-11-02 at 12 31 55" src="https://github.com/intechstudio/grid-fw/assets/57856409/806e84bc-fff6-4566-b296-8f7c86ec0026">

### Debugging
As above, I have recreated this with various permutations of actions on both the button  and encoder event, including leaving both empty. This is recreated on all encoders on both the EN16 and EF44. 

**Other variables explored:**

- Firmware version: This is recreated on v1.2.27, v1.2.26 & v1.2.25. Behaviour does not occur on v1.2.23 and below.
- Bootloader version: Checked the bootloader was updated correctly (I updated some months ago) and went through the update process again to be sure, before retrying firmware versions.
- NVM: Erased NVM in Editor with no change.
- Recovery firmware: Followed steps using the recovery firmware with no change.
- Editor version: Tried re-installing previous versions of Grid Editor with no change.
- Computer, OS, cables etc: The behaviour has been consistent on MacOS, iOS and Windows, as well as with the original USB cable and others.
- No. of modules and position: The behaviour is consitent with one or both modules connected, and in any arrangement, rotation or position.

**Current versions:**

- Editor v1.2.45
- Firmware v1.2.27 (on both modules)
- UF2 Bootloader v1.23.4 SFHWRO
- Model: Bootloader 2023-4b
- Board-ID: SAMD51N20A-GRID

**Comment by joshuahhn** [comment]
I also got this problem at EN16 and EF44.

fun thing: some buttons doesn't have this problem.

**Comment by SukuWc** [comment]
Thanks for the detailed report, based on that we could patch the issue. Please update to latest firmware! Release version v1.2.28
