### ISSUE TITLE
Add instructions how to build the firmware

### ISSUE THREAD

**Issue by ventosus** [intechstudio/grid-fw#65]
I've not managed to build a flasheable uf2 image, yet, can you add instructions to the README please on how to do that?

Here is what I've tried to far:

    $ cd grid_esp
    $ . /opt/esp-idf/export.sh
    $ idf.py build # -> build/grid_fw.bin
    $ idf.py uf2   #  -> build/uf2.bin

The  uf2.bin cannot be flashed successfully  to the device, it is also much smaller than the one already on the device.

**Comment by ventosus** [comment]
Answering my own question:

    $ idf.py build && ./uf2convert.sh -> output/grid_fw.uf2

**Comment by SukuWc** [comment]
Thanks, added it to the README!
