### ISSUE TITLE
Generic RX event for all element types

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-fw#71]
Lua based micro-instrumentation for all elements
- MIDI messages
- SYSEX messages

**Comment by kkerti** [comment]
Does G2G mean cross-module communication? If this is a "multi trigger", reacting to different *state messages* - similar to press-release on button events -, how can we minimise user confusion? Should we create separate *events* in editor for each trigger type, or just come up with a nice group name for the initially mentioned trigger types?

**Comment by SukuWc** [comment]
All of your concerns are valid.  Separate events is not realistic nor scalable. UX considerations will have to be solved on Editor side!
