### ISSUE TITLE
How to build on windows os?

### ISSUE THREAD

**Issue by DRCRecoveryData** [intechstudio/grid-fw#93]
Hi,

Does is possible to build firmware and upload on windows ?

**Comment by DRCRecoveryData** [comment]
> Hi, 
> 
> The easiest way to get started on Windows is by using Docker. There is a dockerfile provided in the repository, it contains all the toolchains needed for building the firmware. Once you have the docker running, you need to execute ```clear && ./pico_build_firmware.sh && ./esp_build_firmware.sh```

Can you tell me where is the main code of bu16? I have plan to made an arcade sanwa version with wood case but the leds model i can't find it on bom files, also the potentiometer, fader and encoder too

**Comment by SukuWc** [comment]
grid_esp32_module_bu16.c describes the BU16 functionality. 
LED part number is: 
WS2812C-2020
I do not know the part number for the UI components, maybe @narayb can help with that!

**Comment by DRCRecoveryData** [comment]
> grid_esp32_module_bu16.c describes the BU16 functionality. 
> 
> LED part number is: 
> 
> WS2812C-2020
> 
> I do not know the part number for the UI components, maybe @narayb can help with that!

Can i use esp32-s3 module instead of the single esp32-s3 chip?

also i wanna know gpio of mux and leds pinout from bu16 to esp32-s3 devkit c to test on breadboard before made pcb

![image](https://github.com/intechstudio/grid-fw/assets/85211068/0299e6b6-4eda-4f87-8fc6-ece0707a8355)

![image](https://github.com/intechstudio/grid-fw/assets/85211068/2acebd6b-9c85-4d28-a856-c6ade75ccf95)
